/**
 * Centralized react-icons (Remix Icon) for a consistent enterprise UI.
 * @see https://react-icons.github.io/react-icons/icons/ri/
 */
import type { IconType } from "react-icons";
import {
  RiAddLine,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiExternalLinkLine,
  RiBuilding2Line,
  RiCalendarCheckLine,
  RiCheckboxCircleLine,
  RiCloseLine,
  RiCustomerService2Line,
  RiDashboardLine,
  RiDownloadCloud2Line,
  RiErrorWarningLine,
  RiFileList3Line,
  RiFileTextLine,
  RiInboxLine,
  RiLoader4Line,
  RiLockLine,
  RiLogoutBoxRLine,
  RiMailLine,
  RiMenuLine,
  RiNotification3Line,
  RiPlayCircleLine,
  RiSearchLine,
  RiSettings3Line,
  RiShieldCheckLine,
  RiShieldKeyholeLine,
  RiTeamLine,
  RiTimeLine,
  RiUploadCloud2Line,
  RiUserAddLine,
  RiUserLine,
  RiBriefcaseLine,
  RiFileCheckLine,
  RiEyeLine,
  RiServerLine,
  RiKey2Line,
  RiPlayLine,
} from "react-icons/ri";

export type { IconType };

export const PlatformIcons = {
  dashboard: RiDashboardLine,
  users: RiTeamLine,
  roles: RiShieldKeyholeLine,
  onboarding: RiUserAddLine,
  documents: RiFileTextLine,
  requests: RiCustomerService2Line,
  point: RiTimeLine,
  admin: RiSettings3Line,
  audit: RiFileList3Line,
  companies: RiBuilding2Line,
  shield: RiShieldCheckLine,
  menu: RiMenuLine,
  close: RiCloseLine,
  chevronRight: RiArrowRightSLine,
  chevronDown: RiArrowDownSLine,
  arrowLeft: RiArrowLeftLine,
  arrowRight: RiArrowRightLine,
  arrowUpRight: RiExternalLinkLine,
  bell: RiNotification3Line,
  search: RiSearchLine,
  logout: RiLogoutBoxRLine,
  user: RiUserLine,
  building: RiBuilding2Line,
  plus: RiAddLine,
  upload: RiUploadCloud2Line,
  download: RiDownloadCloud2Line,
  mail: RiMailLine,
  lock: RiLockLine,
  check: RiCheckboxCircleLine,
  play: RiPlayLine,
  playCircle: RiPlayCircleLine,
  loader: RiLoader4Line,
  inbox: RiInboxLine,
  alert: RiErrorWarningLine,
  file: RiFileTextLine,
  fileCheck: RiFileCheckLine,
  briefcase: RiBriefcaseLine,
  calendar: RiCalendarCheckLine,
  eye: RiEyeLine,
  server: RiServerLine,
  key: RiKey2Line,
} as const;
